"""Add Activities table

Revision ID: 349104c238fb
Revises: e6952c2b5d9c
Create Date: 2026-02-12 10:11:04.274071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349104c238fb'
down_revision = 'e6952c2b5d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('friend_user_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    # ### end Alembic commands ###
