"""Add collection fields and user showcase

Revision ID: 9d4fd3f88430
Revises: 349104c238fb
Create Date: 2026-02-23 22:44:01.668331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4fd3f88430'
down_revision = '349104c238fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_showcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('TOP_MOVIES', 'TOP_TV', 'FAV_SERIES', 'HIDDEN_GEM', name='showcasecategory'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_collection_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_collection_name', sa.String(length=300), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'rank', name='unique_showcase_slot')
    )
    with op.batch_alter_table('user_showcase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_showcase_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_showcase_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_collection_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tmdb_collection_name', sa.String(length=300), nullable=True))
        batch_op.create_index(batch_op.f('ix_media_tmdb_collection_id'), ['tmdb_collection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_tmdb_collection_id'))
        batch_op.drop_column('tmdb_collection_name')
        batch_op.drop_column('tmdb_collection_id')

    with op.batch_alter_table('user_showcase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_showcase_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_showcase_category'))

    op.drop_table('user_showcase')
    # ### end Alembic commands ###
