"""Phase 2

Revision ID: e6952c2b5d9c
Revises: 
Create Date: 2026-02-09 15:12:11.242606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6952c2b5d9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('friendship_id', sa.Integer(), nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED', name='friendshipstatus'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('user_id_1 != user_id_2', name='no_self_friendship'),
    sa.CheckConstraint('user_id_1 < user_id_2', name='ordered_friendship'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('friendship_id'),
    sa.UniqueConstraint('user_id_1', 'user_id_2', name='unique_friendship')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_user_id_1'), ['user_id_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_user_id_2'), ['user_id_2'], unique=False)

    op.create_table('activity_feed',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('ADDED_MEDIA', 'RATED_MEDIA', 'CHANGED_RATING', 'MILESTONE', 'JOINED', name='activitytype'), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    with op.batch_alter_table('activity_feed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_feed_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_feed_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_feed_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('privacy_collection', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('privacy_ratings', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('privacy_stats', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('privacy_profile_searchable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_notifications_friend_requests', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'])
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('email_notifications_friend_requests')
        batch_op.drop_column('privacy_profile_searchable')
        batch_op.drop_column('privacy_stats')
        batch_op.drop_column('privacy_ratings')
        batch_op.drop_column('privacy_collection')
        batch_op.drop_column('bio')
        batch_op.drop_column('display_name')

    with op.batch_alter_table('activity_feed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_feed_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_feed_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_feed_activity_type'))

    op.drop_table('activity_feed')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_user_id_2'))
        batch_op.drop_index(batch_op.f('ix_friendships_user_id_1'))
        batch_op.drop_index(batch_op.f('ix_friendships_status'))

    op.drop_table('friendships')
    # ### end Alembic commands ###
